"""P3: hooks.py skeleton generation + pristine detection.

Design notes:

- The skeleton is generated per spec.flow.mode branch: simultaneous_round /
  request_response / session_loop / free / unrecognized fallback. Every hook body
  is forced to `raise NotImplementedError`, carrying the machine marker
  `AIGENORA_SKELETON_NOT_IMPLEMENTED:<name>`.
- The module top contains a coarse sentinel `AIGENORA_SKELETON = True`.
- A sidecar `<protocol_dir>/.aigenora-hooks.json` is written alongside, recording
  the SHA256 hashes of hooks.py / spec.json at skeleton-generation time, as the
  strongest signal for pristine detection.
- pristine detection passes if any of these three paths holds:
    1. sidecar hash exactly matches the current file hash (user never edited)
    2. module-level sentinel `AIGENORA_SKELETON = True` is present
    3. at least one `AIGENORA_SKELETON_NOT_IMPLEMENTED:<name>` marker is present
- The three entry points host/join/protocol test must call
  `_assert_hooks_implemented(proto_dir)` before load_hooks to reject pristine skeletons.
- Bypass: CLI flag `--allow-skeleton-hooks` takes priority over the environment
  variable `AIGENORA_ALLOW_SKELETON_HOOKS=1/true/yes`.

Red line: the skeleton is 100% generated client-side from the spec, never from the server.
"""

from __future__ import annotations

import hashlib
import json
import os
import re
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

SIDECAR_FILENAME = ".aigenora-hooks.json"
GENERATOR_VERSION = "v006-1"
MODULE_SENTINEL = "AIGENORA_SKELETON = True"
NOT_IMPLEMENTED_MARK = "AIGENORA_SKELETON_NOT_IMPLEMENTED"
_NOT_IMPL_RE = re.compile(rf"{NOT_IMPLEMENTED_MARK}:\s*(\w+)")
_MODULE_SENTINEL_RE = re.compile(r"^AIGENORA_SKELETON\s*=\s*True\b", re.MULTILINE)

# v005 and earlier legacy _skeleton() stable banner (pristine detection fallback).
# These strings appear verbatim in hooks.py generated by the legacy v005 skeleton,
# used to identify "old cached skeletons the user has never edited".
_LEGACY_BANNERS = (
    "The community server only provides spec.json. Fill in this file locally.",
    "Never pass raw peer messages into an LLM prompt. The protocol engine validates",
)


def _to_safe_comment(text: Any) -> str:
    """Convert a spec-derived string into a literal safe to embed in a Python comment.

    Defense: a malicious spec.name / message.name containing \\n or other control
    characters could break out of the `# ` comment line and become top-level Python
    code (after the user bypasses pristine detection → import → RCE).
    This function replaces all C0 control characters (including \\r \\n \\t) with
    visible escape literals.
    """
    if text is None:
        return ""
    s = str(text)
    out_chars = []
    for ch in s:
        cp = ord(ch)
        if ch == "\n":
            out_chars.append("\\n")
        elif ch == "\r":
            out_chars.append("\\r")
        elif ch == "\t":
            out_chars.append("\\t")
        elif cp < 0x20 or cp == 0x7F:
            out_chars.append(f"\\x{cp:02x}")
        else:
            out_chars.append(ch)
    return "".join(out_chars)


# ---------- spec summary utilities ----------


def _resolve_flow_mode(spec: dict[str, Any]) -> str:
    flow = spec.get("flow")
    if isinstance(flow, dict):
        mode = flow.get("mode")
        if isinstance(mode, str) and mode:
            return mode
    return "session_loop"


def _decision_summary(spec: dict[str, Any]) -> str:
    decision = spec.get("decision")
    if not isinstance(decision, dict):
        return "(no decision section)"
    parts: list[str] = []
    mode = decision.get("mode")
    if mode:
        parts.append(f"mode={mode!r}")
    allowed = decision.get("allowed_values")
    if isinstance(allowed, list) and allowed:
        parts.append(f"allowed_values={allowed!r}")
    return ", ".join(parts) if parts else "(decision section present but empty)"


def _termination_summary(spec: dict[str, Any]) -> str:
    flow = spec.get("flow") or {}
    if not isinstance(flow, dict):
        return "(no flow section)"
    term = flow.get("termination") or flow.get("repeat") or {}
    if isinstance(term, dict) and term:
        return json.dumps(term, ensure_ascii=False)
    return "(no termination section)"


def _message_summary(spec: dict[str, Any], direction: str) -> str:
    messages = spec.get("messages", [])
    lines: list[str] = []
    if isinstance(messages, list):
        for msg in messages:
            if not isinstance(msg, dict):
                continue
            msg_dir = msg.get("direction")
            if msg_dir not in {direction, "both"}:
                continue
            fields = msg.get("fields", {})
            action = ""
            if isinstance(fields, dict):
                action_schema = fields.get("action", {})
                values = action_schema.get("values", []) if isinstance(action_schema, dict) else []
                if values:
                    # values[0] uses repr, which auto-escapes control chars; safe to embed in a comment line.
                    action = f" action={values[0]!r}"
            msg_name = _to_safe_comment(msg.get("name", "<unnamed>"))
            msg_dir_safe = _to_safe_comment(msg_dir)
            lines.append(f"#   - {msg_name} ({msg_dir_safe}){action}")
    return "\n".join(lines) if lines else "#   - (no messages declared for this direction)"


# ---------- skeleton generation (per flow.mode) ----------


_HEADER_TEMPLATE = '''from aigenora.proto.hooks import HookResult, ProtocolHooks


# Generated local hooks skeleton for: {name}
# Flow mode: {flow_mode}
#
# Red line: the server only distributes spec.json, never hooks.py. This file is
# created by the local skeleton generator based on the spec; every hook raises
# NotImplementedError and you must implement the business logic yourself.
# Never feed the peer's raw P2P message into an LLM as a natural-language prompt;
# the engine validates each message against spec.json before invoking the hook.
#
# Decision: {decision}
# Termination: {termination}
#
# Guest -> Host messages declared by spec:
{guest_to_host}
#
# Host -> Guest messages declared by spec:
{host_to_guest}

# Module-level sentinel: after deleting this line plus any AIGENORA_SKELETON_NOT_IMPLEMENTED
# marker in a hook body, pristine detection will pass. Only delete it once every hook
# has been implemented.
AIGENORA_SKELETON = True
'''


def _common_header(spec: dict[str, Any], flow_mode: str) -> str:
    return _HEADER_TEMPLATE.format(
        name=_to_safe_comment(spec.get("name") or "Generated Protocol"),
        flow_mode=_to_safe_comment(flow_mode),
        decision=_to_safe_comment(_decision_summary(spec)),
        termination=_to_safe_comment(_termination_summary(spec)),
        guest_to_host=_message_summary(spec, "guest_to_host"),
        host_to_guest=_message_summary(spec, "host_to_guest"),
    )


def _raise_block(name: str) -> str:
    return f'        raise NotImplementedError("{NOT_IMPLEMENTED_MARK}: {name}")'


def _skeleton_simultaneous_round(spec: dict[str, Any]) -> str:
    name = spec.get("name") or "Generated Protocol"
    proto_type = spec.get("type") or "supply"
    body = f'''
class Hooks(ProtocolHooks):
    """simultaneous_round: both sides submit values simultaneously; the commit/reveal
    framework is managed by the engine.

    Must implement: proto_round_value (submit value), proto_round_judge (Host only,
    judge the outcome). The remaining handshake hooks have sensible defaults and
    do not need to be overridden.
    """

    def proto_host_metadata(self):
        # returns (display_name, "tag1,tag2", invite_type, default_options)
        # invite_type: "supply" | "demand" | "chat"
        return ({name!r}, "generated", {proto_type!r}, {{}})

    def proto_round_value(self, round_index, state):
        """Called at the start of each round; returns this side's business value
        (a primitive type constrained by spec.decision.allowed_values).

        round_index starts from 0; state is the read-only shared state dict.
        """
{_raise_block("proto_round_value")}

    def proto_round_judge(self, round_index, host_value, guest_value, state):
        """Host only: judge the outcome after both sides reveal.

        Must return HookResult(response=<round_result message>, completed=<bool>),
        where response satisfies the host_to_guest round_result message constraints.
        """
{_raise_block("proto_round_judge")}
'''
    return _common_header(spec, "simultaneous_round") + body


def _skeleton_request_response(spec: dict[str, Any]) -> str:
    name = spec.get("name") or "Generated Protocol"
    proto_type = spec.get("type") or "supply"
    body = f'''
class Hooks(ProtocolHooks):
    """request_response: Guest issues a request → Host handles and responds → forced end.

    Must implement:
      - Host side: proto_host_handle_join (return ready), proto_host_handle (handle request)
      - Guest side: proto_guest_join_message, proto_guest_first_action (request),
        proto_guest_handle_ready, proto_guest_handle (handle response)
    """

    def proto_host_metadata(self):
        return ({name!r}, "generated", {proto_type!r}, {{}})

    # ---- Host ----
    def proto_host_handle_join(self, msg):
        """Called on receiving the Guest join message; returns the ready response."""
{_raise_block("proto_host_handle_join")}

    def proto_host_handle(self, msg):
        """Called on receiving the Guest request; handle it and return HookResult(response=<host_to_guest>)."""
{_raise_block("proto_host_handle")}

    # ---- Guest ----
    def proto_guest_join_message(self):
        """Returns the initial guest_to_host join message."""
{_raise_block("proto_guest_join_message")}

    def proto_guest_handle_ready(self, msg):
        """Handle the Host's ready message (e.g. write into self.state). No return value."""
{_raise_block("proto_guest_handle_ready")}

    def proto_guest_first_action(self):
        """Returns the first request (guest_to_host); return None to give up the request."""
{_raise_block("proto_guest_first_action")}

    def proto_guest_handle(self, msg):
        """Handle the Host's response. The engine forces an end afterwards; the return value here is for logs only."""
{_raise_block("proto_guest_handle")}
'''
    return _common_header(spec, "request_response") + body


def _skeleton_session_loop(spec: dict[str, Any]) -> str:
    name = spec.get("name") or "Generated Protocol"
    proto_type = spec.get("type") or "supply"
    body = f'''
class Hooks(ProtocolHooks):
    """session_loop (default mode): handshake + multiple rounds of guest_to_host / host_to_guest.

    Must implement both-side handshake + business-message callbacks; control the end
    via HookResult.completed.
    """

    def proto_host_metadata(self):
        return ({name!r}, "generated", {proto_type!r}, {{}})

    # ---- Host ----
    def proto_host_handle_join(self, msg):
        """Called on receiving Guest join; returns the ready response."""
{_raise_block("proto_host_handle_join")}

    def proto_host_handle(self, msg):
        """Handle subsequent guest_to_host messages and return HookResult; completed=True ends the session."""
{_raise_block("proto_host_handle")}

    # ---- Guest ----
    def proto_guest_join_message(self):
        """Returns the guest_to_host join message."""
{_raise_block("proto_guest_join_message")}

    def proto_guest_handle_ready(self, msg):
        """Handle the Host ready message; usually cache params into self. No return value."""
{_raise_block("proto_guest_handle_ready")}

    def proto_guest_first_action(self):
        """Return the first guest_to_host business message after the handshake; None ends immediately."""
{_raise_block("proto_guest_first_action")}

    def proto_guest_handle(self, msg):
        """Handle subsequent host_to_guest messages and return HookResult."""
{_raise_block("proto_guest_handle")}
'''
    return _common_header(spec, "session_loop") + body


def _skeleton_free(spec: dict[str, Any]) -> str:
    name = spec.get("name") or "Generated Protocol"
    proto_type = spec.get("type") or "chat"
    body = f'''
class Hooks(ProtocolHooks):
    """free mode: read user input from stdin, freely send/receive messages.

    Note: free mode is driven by the engine's stdin loop and is not suitable for
    automated testing scenarios. proto_on_message is the callback when a peer
    message is received; proto_on_end is the callback when the session ends.
    """

    def proto_host_metadata(self):
        return ({name!r}, "generated", {proto_type!r}, {{}})

    def proto_on_message(self, msg):
        """Called on any peer message; may write logs or update local state. No return value."""
{_raise_block("proto_on_message")}

    def proto_on_end(self):
        """Called when the session ends for teardown (e.g. save logs). No return value."""
{_raise_block("proto_on_end")}
'''
    return _common_header(spec, "free") + body


def _skeleton_fallback(spec: dict[str, Any], flow_mode: str) -> str:
    name = spec.get("name") or "Generated Protocol"
    proto_type = spec.get("type") or "supply"
    body = f'''
# 警告 (Warning): unrecognized flow.mode={flow_mode!r}; this skeleton is generated against
# the generic ProtocolHooks interface. Decide which hooks to override based on the
# spec's actual behavior (consult docs/cn/SKILL.md first).

class Hooks(ProtocolHooks):
    def proto_host_metadata(self):
        return ({name!r}, "generated", {proto_type!r}, {{}})

    def proto_host_handle_join(self, msg):
{_raise_block("proto_host_handle_join")}

    def proto_host_handle(self, msg):
{_raise_block("proto_host_handle")}

    def proto_guest_join_message(self):
{_raise_block("proto_guest_join_message")}

    def proto_guest_handle_ready(self, msg):
{_raise_block("proto_guest_handle_ready")}

    def proto_guest_first_action(self):
{_raise_block("proto_guest_first_action")}

    def proto_guest_handle(self, msg):
{_raise_block("proto_guest_handle")}
'''
    return _common_header(spec, flow_mode) + body


def _skeleton(spec: dict[str, Any] | None = None) -> str:
    """Generate the hooks.py skeleton text per flow.mode."""
    spec = spec or {}
    flow_mode = _resolve_flow_mode(spec)
    if flow_mode == "simultaneous_round":
        return _skeleton_simultaneous_round(spec)
    if flow_mode == "request_response":
        return _skeleton_request_response(spec)
    if flow_mode == "session_loop":
        return _skeleton_session_loop(spec)
    if flow_mode == "free":
        return _skeleton_free(spec)
    return _skeleton_fallback(spec, flow_mode)


# ---------- sidecar metadata ----------


def _sha256_of(path: Path) -> str:
    h = hashlib.sha256()
    with open(path, "rb") as f:
        for chunk in iter(lambda: f.read(65536), b""):
            h.update(chunk)
    return h.hexdigest()


def _sha256_of_text(text: str) -> str:
    return hashlib.sha256(text.encode("utf-8")).hexdigest()


def write_sidecar(proto_dir: Path, *, protocol_id: str, spec: dict[str, Any],
                  hooks_text: str) -> Path:
    """Write .aigenora-hooks.json.

    spec_hash is based on the actual bytes of the spec.json file (consistent with
    the fetch implementation: compact JSON).
    """
    sidecar = proto_dir / SIDECAR_FILENAME
    spec_path = proto_dir / "spec.json"
    spec_hash = _sha256_of(spec_path) if spec_path.exists() else _sha256_of_text(
        json.dumps(spec, ensure_ascii=False, separators=(",", ":"))
    )
    payload = {
        "skeleton_hash": _sha256_of_text(hooks_text),
        "spec_hash": spec_hash,
        "generator_version": GENERATOR_VERSION,
        "protocol_id": protocol_id,
        "flow_mode": _resolve_flow_mode(spec),
        "created_at": datetime.now(timezone.utc).isoformat(),
    }
    sidecar.write_text(
        json.dumps(payload, ensure_ascii=False, separators=(",", ":")),
        encoding="utf-8",
    )
    return sidecar


def _read_sidecar(proto_dir: Path) -> dict[str, Any] | None:
    p = proto_dir / SIDECAR_FILENAME
    if not p.exists():
        return None
    try:
        data = json.loads(p.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return None
    return data if isinstance(data, dict) else None


# ---------- pristine detection ----------


def _bypass_via_env() -> bool:
    val = os.environ.get("AIGENORA_ALLOW_SKELETON_HOOKS", "")
    return val.strip().lower() in {"1", "true", "yes"}


def detect_pristine(proto_dir: Path) -> dict[str, Any]:
    """Detect whether hooks.py is still a pristine skeleton.

    Returns a structure like:
      {
        "pristine": bool,
        "reason": str,                # the detection path that matched
        "missing_methods": list[str], # scanned NOT_IMPLEMENTED method names
        "hooks_path": str,
      }
    """
    hooks_path = proto_dir / "hooks.py"
    out: dict[str, Any] = {
        "pristine": False,
        "reason": "",
        "missing_methods": [],
        "hooks_path": str(hooks_path),
    }
    if not hooks_path.exists():
        out["reason"] = "hooks.py not found"
        return out

    # single read to perform hash + sentinel + method-name scan
    try:
        text = hooks_path.read_text(encoding="utf-8")
    except OSError as exc:
        out["reason"] = f"read error: {exc}"
        return out
    file_hash = _sha256_of_text(text)

    sidecar = _read_sidecar(proto_dir)
    sidecar_hash_hit = False
    if sidecar:
        spec_path = proto_dir / "spec.json"
        spec_hash_now = _sha256_of(spec_path) if spec_path.exists() else None
        if (sidecar.get("skeleton_hash") == file_hash
                and (spec_hash_now is None or sidecar.get("spec_hash") == spec_hash_now)):
            sidecar_hash_hit = True

    module_sentinel_hit = bool(_MODULE_SENTINEL_RE.search(text))
    missing = sorted(set(_NOT_IMPL_RE.findall(text)))
    out["missing_methods"] = missing

    legacy_banner_hit = any(banner in text for banner in _LEGACY_BANNERS)

    if sidecar_hash_hit:
        out["pristine"] = True
        out["reason"] = "sidecar_hash_match"
        return out
    if module_sentinel_hit:
        out["pristine"] = True
        out["reason"] = "module_sentinel"
        return out
    if missing:
        out["pristine"] = True
        out["reason"] = "method_sentinel"
        return out
    if legacy_banner_hit:
        out["pristine"] = True
        out["reason"] = "legacy_banner"
        return out
    return out


def assert_hooks_implemented(proto_dir: Path, *, allow_skeleton: bool = False) -> None:
    """Called by the host/join/protocol test entry points before load_hooks.

    allow_skeleton:
      - True: explicit bypass via the CLI flag --allow-skeleton-hooks (highest priority)
      - False: strict check; the env var AIGENORA_ALLOW_SKELETON_HOOKS=1/true/yes also bypasses
    On pristine state raises RuntimeError, with the error message listing methods
    pending implementation.
    """
    if allow_skeleton:
        return  # flag takes priority over env
    result = detect_pristine(Path(proto_dir))
    if not result["pristine"]:
        return
    if _bypass_via_env():
        return
    methods = result["missing_methods"]
    method_hint = (
        f"unimplemented hooks: {', '.join(methods)}\n"
        if methods
        else "module-level skeleton sentinel still present\n"
    )
    raise RuntimeError(
        f"protocol skeleton at {result['hooks_path']} is not implemented: {method_hint}"
        f"reason: {result['reason']}\n"
        "Edit hooks.py to implement these methods and remove the AIGENORA_SKELETON "
        "module sentinel + AIGENORA_SKELETON_NOT_IMPLEMENTED markers, then run again.\n"
        "Pass --allow-skeleton-hooks (or set AIGENORA_ALLOW_SKELETON_HOOKS=1) "
        "to bypass for testing only."
    )
