from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class ErrorDetail:
    code: str
    message: str


class VsdpError(ValueError):
    """Stable, fail-closed VSDP validation error."""

    def __init__(self, code: str, message: str):
        super().__init__(f"{code}: {message}")
        self.code = code
        self.message = message

    def as_dict(self) -> dict[str, str]:
        return {"code": self.code, "message": self.message}


UNKNOWN_PROFILE = "VSDP_UNKNOWN_PROFILE"
NON_CANONICAL = "VSDP_NON_CANONICAL"
CONTEXT_MISMATCH = "VSDP_CONTEXT_MISMATCH"
CANDIDATE_DIGEST_MISMATCH = "VSDP_CANDIDATE_DIGEST_MISMATCH"
ELIGIBILITY_MESSAGE_MISMATCH = "VSDP_ELIGIBILITY_MESSAGE_MISMATCH"
ELIGIBILITY_SCOPE_MISMATCH = "VSDP_ELIGIBILITY_SCOPE_MISMATCH"
ELIGIBILITY_ROOT_MISMATCH = "VSDP_ELIGIBILITY_ROOT_MISMATCH"
ELIGIBILITY_PROOF_INVALID = "VSDP_ELIGIBILITY_PROOF_INVALID"
BALLOT_PROOF_INVALID = "VSDP_BALLOT_PROOF_INVALID"
NULLIFIER_CONFLICT = "VSDP_NULLIFIER_CONFLICT"
RECEIPT_QUORUM_MISSING = "VSDP_RECEIPT_QUORUM_MISSING"
BOARD_FORK = "VSDP_BOARD_FORK"
RECEIPTED_RECORD_MISSING = "VSDP_RECEIPTED_RECORD_MISSING"
CHALLENGED_BALLOT_INCLUDED = "VSDP_CHALLENGED_BALLOT_INCLUDED"
ANONYMITY_SET_TOO_SMALL = "VSDP_ANONYMITY_SET_TOO_SMALL"
DECRYPTION_UNAUTHORIZED = "VSDP_DECRYPTION_UNAUTHORIZED"
DECRYPTION_REPLAY = "VSDP_DECRYPTION_REPLAY"
DECRYPTION_SHARE_INVALID = "VSDP_DECRYPTION_SHARE_INVALID"
TALLY_MISMATCH = "VSDP_TALLY_MISMATCH"
UNRESOLVED_DISPUTE = "VSDP_UNRESOLVED_DISPUTE"
INVALID_TRANSITION = "VSDP_INVALID_TRANSITION"
ARTIFACT_HASH_MISMATCH = "VSDP_ARTIFACT_HASH_MISMATCH"
ROLE_ASSIGNMENT_INVALID = "VSDP_ROLE_ASSIGNMENT_INVALID"
ROLE_CHANNEL_VIOLATION = "VSDP_ROLE_CHANNEL_VIOLATION"
CONTRIBUTION_CONFLICT = "VSDP_CONTRIBUTION_CONFLICT"
QUORUM_TIMEOUT = "VSDP_QUORUM_TIMEOUT"
CEREMONY_ABORTED = "VSDP_CEREMONY_ABORTED"
BUS_DISCONNECTED = "VSDP_BUS_DISCONNECTED"
VOTING_NOT_OPEN = "VSDP_VOTING_NOT_OPEN"
VOTING_CLOSED = "VSDP_VOTING_CLOSED"
