from __future__ import annotations

import copy
import hashlib
import json
import os
import pprint
import re
import shutil
import tempfile
import time
import uuid
from importlib import resources
from pathlib import Path
from typing import Any

from aigenora.engine.crypto import protocol_hash_from_obj
from aigenora.engine.keys import keygen
from aigenora.proto.group import GroupAuthority
from aigenora.proto.loader import load_hooks
from aigenora.proto.validate import load_spec


GAME_KIT_SCHEMA = "aigenora-game-kit/1"
BUILD_MARKER_SCHEMA = "aigenora-game-kit-build/1"
BUILD_MARKER = ".aigenora-game-kit.json"
SUPPORTED_PRESETS = ("duel", "choice-matrix", "arcade")
SUPPORTED_THEMES = ("ember", "jade", "neon")
_SLUG_RE = re.compile(r"^[a-z][a-z0-9_-]{0,23}$")
_COLOR_RE = re.compile(r"^#[0-9a-fA-F]{6}$")


class GameKitError(ValueError):
    """A manifest or generated bundle violates the Game Kit contract."""


_DEFAULT_DUEL_MANIFEST: dict[str, Any] = {
    "schema": GAME_KIT_SCHEMA,
    "preset": "duel",
    "name": "Aigenora Quick Duel",
    "tagline": "Read the field. Shape the tempo. Break the rival signal.",
    "description": (
        "A fast Host-authoritative tactical duel generated by Aigenora Game Kit. "
        "Players alternate actions until one signal remains."
    ),
    "players": 2,
    "theme": "ember",
    "combat": {
        "starting_health": 24,
        "starting_energy": 1,
        "max_energy": 5,
        "energy_per_turn": 1,
        "max_turns": 60,
    },
    "actions": [
        {
            "id": "strike",
            "label": "Signal Strike",
            "description": "Deal focused damage and recover one energy.",
            "effect": "damage",
            "power": 5,
            "cost": 0,
            "gain": 1,
            "glyph": "✦",
        },
        {
            "id": "aegis",
            "label": "Aegis Weave",
            "description": "Convert energy into a persistent shield.",
            "effect": "guard",
            "power": 6,
            "cost": 1,
            "gain": 0,
            "glyph": "◇",
        },
        {
            "id": "mend",
            "label": "Quiet Mend",
            "description": "Restore health without exceeding the starting limit.",
            "effect": "heal",
            "power": 5,
            "cost": 2,
            "gain": 0,
            "glyph": "+",
        },
        {
            "id": "nova",
            "label": "Nova Chorus",
            "description": "Spend a full charge to damage every active rival.",
            "effect": "damage_all",
            "power": 8,
            "cost": 3,
            "gain": 0,
            "glyph": "✺",
        },
    ],
}


_DEFAULT_MATRIX_MANIFEST: dict[str, Any] = {
    "schema": GAME_KIT_SCHEMA,
    "preset": "choice-matrix",
    "name": "RPS · The Well Variant",
    "tagline": "Four signs. Six matchups. One sealed choice each round.",
    "description": (
        "A content-addressed Rock-Paper-Scissors variant with the Well as a fourth "
        "choice. Every move is committed before either side reveals it."
    ),
    "players": 2,
    "theme": "jade",
    "match": {"rounds_to_win": 2, "max_rounds": 7},
    "choices": [
        {
            "id": "rock",
            "label": "Rock",
            "description": "Crushes scissors; sinks into the well.",
            "glyph": "✊",
            "color": "#ef8a58",
            "beats": ["scissors"],
        },
        {
            "id": "paper",
            "label": "Paper",
            "description": "Covers rock and seals the well.",
            "glyph": "✋",
            "color": "#f2cf68",
            "beats": ["rock", "well"],
        },
        {
            "id": "scissors",
            "label": "Scissors",
            "description": "Cuts paper; falls into the well.",
            "glyph": "✌",
            "color": "#67c6b3",
            "beats": ["paper"],
        },
        {
            "id": "well",
            "label": "The Well",
            "description": "Swallows rock and scissors; paper seals it.",
            "glyph": "◉",
            "color": "#7288d8",
            "beats": ["rock", "scissors"],
        },
    ],
}


_DEFAULT_ARCADE_MAP = [
    "#####################",
    "#P......B...B......P#",
    "#.......B...B.......#",
    "#..SS...........SS..#",
    "#.......WWW.........#",
    "#...................#",
    "#....B.........B....#",
    "#...................#",
    "#.........WWW.......#",
    "#..SS...........SS..#",
    "#.......B...B.......#",
    "#P......B...B......P#",
    "#####################",
]


_DEFAULT_ARCADE_MANIFEST: dict[str, Any] = {
    "schema": GAME_KIT_SCHEMA,
    "preset": "arcade",
    "name": "Skyline Intercept",
    "tagline": "Thread the ruins, seize shield cores, break the opposing wing.",
    "description": (
        "A Host-authoritative real-time aircraft duel generated from a bounded "
        "Aigenora arcade blueprint."
    ),
    "players": 2,
    "theme": "neon",
    "vehicle": {
        "kind": "aircraft",
        "label": "Interceptor",
        "movement": "air",
        "primary": "#76e6ff",
        "accent": "#ffbf69",
    },
    "arena": {
        "map": _DEFAULT_ARCADE_MAP,
        "team_size": 2,
        "friendly_fire": False,
    },
    "balance": {
        "hp": 4,
        "speed": 220,
        "fire_cooldown": 6,
        "bullet_speed": 640,
    },
    "pickups": ["shield", "rapid", "repair", "speed"],
    "pickup_duration_ticks": 90,
    "victory": {
        "mode": "first_to_score",
        "target_score": 1,
        "max_ticks": 240,
    },
}


_DEFAULT_MANIFESTS = {
    "duel": _DEFAULT_DUEL_MANIFEST,
    "choice-matrix": _DEFAULT_MATRIX_MANIFEST,
    "arcade": _DEFAULT_ARCADE_MANIFEST,
}


def default_manifest(preset: str = "duel") -> dict[str, Any]:
    try:
        value = _DEFAULT_MANIFESTS[preset]
    except KeyError as exc:
        raise GameKitError(
            f"preset must be one of: {', '.join(SUPPORTED_PRESETS)}"
        ) from exc
    return copy.deepcopy(value)


def _text(value: Any, field: str, *, minimum: int, maximum: int) -> str:
    if not isinstance(value, str):
        raise GameKitError(f"{field} must be a string")
    normalized = " ".join(value.strip().split())
    size = len(normalized.encode("utf-8"))
    if size < minimum or size > maximum:
        raise GameKitError(
            f"{field} must contain between {minimum} and {maximum} UTF-8 bytes"
        )
    return normalized


def _integer(
    value: Any,
    field: str,
    *,
    minimum: int,
    maximum: int,
) -> int:
    if not isinstance(value, int) or isinstance(value, bool):
        raise GameKitError(f"{field} must be an integer")
    if value < minimum or value > maximum:
        raise GameKitError(f"{field} must be between {minimum} and {maximum}")
    return value


def _merge_manifest(raw: dict[str, Any]) -> dict[str, Any]:
    preset = raw.get("preset", "duel")
    if preset not in SUPPORTED_PRESETS:
        raise GameKitError(
            f"preset must be one of: {', '.join(SUPPORTED_PRESETS)}"
        )
    merged = default_manifest(str(preset))
    for key, value in raw.items():
        if key in {"combat", "match", "vehicle", "arena", "balance", "victory"} and isinstance(value, dict):
            existing = merged.get(key)
            if isinstance(existing, dict):
                existing.update(copy.deepcopy(value))
            else:
                merged[key] = copy.deepcopy(value)
        else:
            merged[key] = copy.deepcopy(value)
    return merged


def _normalize_duel_manifest(value: dict[str, Any]) -> dict[str, Any]:
    allowed = {
        "schema",
        "preset",
        "name",
        "tagline",
        "description",
        "players",
        "theme",
        "combat",
        "actions",
    }
    unknown = sorted(set(value) - allowed)
    if unknown:
        raise GameKitError(f"game manifest has unknown fields: {unknown!r}")
    merged = _merge_manifest(value)
    if merged.get("schema") != GAME_KIT_SCHEMA:
        raise GameKitError(f"game manifest schema must be {GAME_KIT_SCHEMA!r}")
    preset = merged.get("preset")
    if preset != "duel":
        raise GameKitError("duel normalizer received a different preset")
    theme = merged.get("theme")
    if theme not in SUPPORTED_THEMES:
        raise GameKitError(
            f"theme must be one of: {', '.join(SUPPORTED_THEMES)}"
        )
    combat = merged.get("combat")
    if not isinstance(combat, dict):
        raise GameKitError("combat must be an object")
    combat_allowed = {
        "starting_health",
        "starting_energy",
        "max_energy",
        "energy_per_turn",
        "max_turns",
    }
    combat_unknown = sorted(set(combat) - combat_allowed)
    if combat_unknown:
        raise GameKitError(f"combat has unknown fields: {combat_unknown!r}")
    normalized_combat = {
        "starting_health": _integer(
            combat.get("starting_health"),
            "combat.starting_health",
            minimum=8,
            maximum=999,
        ),
        "starting_energy": _integer(
            combat.get("starting_energy"),
            "combat.starting_energy",
            minimum=0,
            maximum=99,
        ),
        "max_energy": _integer(
            combat.get("max_energy"),
            "combat.max_energy",
            minimum=1,
            maximum=99,
        ),
        "energy_per_turn": _integer(
            combat.get("energy_per_turn"),
            "combat.energy_per_turn",
            minimum=0,
            maximum=20,
        ),
        "max_turns": _integer(
            combat.get("max_turns"),
            "combat.max_turns",
            minimum=4,
            maximum=500,
        ),
    }
    if normalized_combat["starting_energy"] > normalized_combat["max_energy"]:
        raise GameKitError("combat.starting_energy cannot exceed combat.max_energy")

    raw_actions = merged.get("actions")
    if not isinstance(raw_actions, list) or not 2 <= len(raw_actions) <= 6:
        raise GameKitError("actions must contain between 2 and 6 entries")
    normalized_actions: list[dict[str, Any]] = []
    seen: set[str] = set()
    effects = {"damage", "damage_all", "guard", "heal", "charge"}
    for index, raw_action in enumerate(raw_actions):
        field = f"actions[{index}]"
        if not isinstance(raw_action, dict):
            raise GameKitError(f"{field} must be an object")
        action_allowed = {
            "id",
            "label",
            "description",
            "effect",
            "power",
            "cost",
            "gain",
            "glyph",
        }
        action_unknown = sorted(set(raw_action) - action_allowed)
        if action_unknown:
            raise GameKitError(f"{field} has unknown fields: {action_unknown!r}")
        action_id = raw_action.get("id")
        if not isinstance(action_id, str) or not _SLUG_RE.fullmatch(action_id):
            raise GameKitError(f"{field}.id must be a lowercase action slug")
        if action_id in seen:
            raise GameKitError(f"duplicate action id: {action_id}")
        seen.add(action_id)
        effect = raw_action.get("effect")
        if effect not in effects:
            raise GameKitError(
                f"{field}.effect must be one of: {', '.join(sorted(effects))}"
            )
        action = {
            "id": action_id,
            "label": _text(
                raw_action.get("label"), f"{field}.label", minimum=1, maximum=48
            ),
            "description": _text(
                raw_action.get("description"),
                f"{field}.description",
                minimum=1,
                maximum=180,
            ),
            "effect": effect,
            "power": _integer(
                raw_action.get("power"),
                f"{field}.power",
                minimum=1,
                maximum=99,
            ),
            "cost": _integer(
                raw_action.get("cost"),
                f"{field}.cost",
                minimum=0,
                maximum=99,
            ),
            "gain": _integer(
                raw_action.get("gain", 0),
                f"{field}.gain",
                minimum=0,
                maximum=20,
            ),
            "glyph": _text(
                raw_action.get("glyph", "•"),
                f"{field}.glyph",
                minimum=1,
                maximum=12,
            ),
        }
        if action["cost"] > normalized_combat["max_energy"]:
            raise GameKitError(
                f"{field}.cost exceeds combat.max_energy and can never be paid"
            )
        normalized_actions.append(action)
    if not any(action["effect"] in {"damage", "damage_all"} for action in normalized_actions):
        raise GameKitError("at least one damage or damage_all action is required")
    if not any(action["cost"] == 0 for action in normalized_actions):
        raise GameKitError("at least one zero-cost action is required to prevent deadlock")

    return {
        "schema": GAME_KIT_SCHEMA,
        "preset": str(preset),
        "name": _text(merged.get("name"), "name", minimum=1, maximum=96),
        "tagline": _text(
            merged.get("tagline"), "tagline", minimum=1, maximum=240
        ),
        "description": _text(
            merged.get("description"), "description", minimum=1, maximum=800
        ),
        "players": _integer(
            merged.get("players"), "players", minimum=2, maximum=4
        ),
        "theme": str(theme),
        "combat": normalized_combat,
        "actions": normalized_actions,
    }


def _metadata(merged: dict[str, Any], *, players: int) -> dict[str, Any]:
    theme = merged.get("theme")
    if theme not in SUPPORTED_THEMES:
        raise GameKitError(
            f"theme must be one of: {', '.join(SUPPORTED_THEMES)}"
        )
    return {
        "schema": GAME_KIT_SCHEMA,
        "preset": str(merged["preset"]),
        "name": _text(merged.get("name"), "name", minimum=1, maximum=96),
        "tagline": _text(
            merged.get("tagline"), "tagline", minimum=1, maximum=240
        ),
        "description": _text(
            merged.get("description"), "description", minimum=1, maximum=800
        ),
        "players": players,
        "theme": str(theme),
    }


def _normalize_matrix_manifest(value: dict[str, Any]) -> dict[str, Any]:
    allowed = {
        "schema",
        "preset",
        "name",
        "tagline",
        "description",
        "players",
        "theme",
        "match",
        "choices",
    }
    unknown = sorted(set(value) - allowed)
    if unknown:
        raise GameKitError(f"game manifest has unknown fields: {unknown!r}")
    merged = _merge_manifest(value)
    if merged.get("schema") != GAME_KIT_SCHEMA:
        raise GameKitError(f"game manifest schema must be {GAME_KIT_SCHEMA!r}")
    if merged.get("preset") != "choice-matrix":
        raise GameKitError("choice-matrix normalizer received a different preset")
    if merged.get("players") != 2:
        raise GameKitError("choice-matrix requires exactly two players")
    match = merged.get("match")
    if not isinstance(match, dict):
        raise GameKitError("match must be an object")
    match_unknown = sorted(set(match) - {"rounds_to_win", "max_rounds"})
    if match_unknown:
        raise GameKitError(f"match has unknown fields: {match_unknown!r}")
    normalized_match = {
        "rounds_to_win": _integer(
            match.get("rounds_to_win"),
            "match.rounds_to_win",
            minimum=1,
            maximum=99,
        ),
        "max_rounds": _integer(
            match.get("max_rounds"), "match.max_rounds", minimum=1, maximum=199
        ),
    }
    if normalized_match["rounds_to_win"] > normalized_match["max_rounds"]:
        raise GameKitError("match.rounds_to_win cannot exceed match.max_rounds")
    raw_choices = merged.get("choices")
    if not isinstance(raw_choices, list) or not 3 <= len(raw_choices) <= 9:
        raise GameKitError("choices must contain between 3 and 9 entries")
    normalized_choices: list[dict[str, Any]] = []
    ids: set[str] = set()
    for index, raw_choice in enumerate(raw_choices):
        field = f"choices[{index}]"
        if not isinstance(raw_choice, dict):
            raise GameKitError(f"{field} must be an object")
        choice_unknown = sorted(
            set(raw_choice)
            - {"id", "label", "description", "glyph", "color", "beats"}
        )
        if choice_unknown:
            raise GameKitError(f"{field} has unknown fields: {choice_unknown!r}")
        choice_id = raw_choice.get("id")
        if not isinstance(choice_id, str) or not _SLUG_RE.fullmatch(choice_id):
            raise GameKitError(f"{field}.id must be a lowercase choice slug")
        if choice_id in ids:
            raise GameKitError(f"duplicate choice id: {choice_id}")
        ids.add(choice_id)
        color = raw_choice.get("color")
        if not isinstance(color, str) or not _COLOR_RE.fullmatch(color):
            raise GameKitError(f"{field}.color must be a six-digit hex color")
        beats = raw_choice.get("beats")
        if not isinstance(beats, list) or any(not isinstance(item, str) for item in beats):
            raise GameKitError(f"{field}.beats must be a list of choice ids")
        if len(set(beats)) != len(beats):
            raise GameKitError(f"{field}.beats must not contain duplicates")
        normalized_choices.append(
            {
                "id": choice_id,
                "label": _text(
                    raw_choice.get("label"), f"{field}.label", minimum=1, maximum=48
                ),
                "description": _text(
                    raw_choice.get("description"),
                    f"{field}.description",
                    minimum=1,
                    maximum=180,
                ),
                "glyph": _text(
                    raw_choice.get("glyph", "•"),
                    f"{field}.glyph",
                    minimum=1,
                    maximum=12,
                ),
                "color": color.lower(),
                "beats": list(beats),
            }
        )
    by_id = {item["id"]: item for item in normalized_choices}
    for item in normalized_choices:
        unknown_beats = sorted(set(item["beats"]) - set(by_id))
        if unknown_beats:
            raise GameKitError(
                f"choice {item['id']} beats unknown choices: {unknown_beats!r}"
            )
        if item["id"] in item["beats"]:
            raise GameKitError(f"choice {item['id']} cannot beat itself")
    for left_index, left in enumerate(normalized_choices):
        for right in normalized_choices[left_index + 1 :]:
            left_beats = right["id"] in left["beats"]
            right_beats = left["id"] in right["beats"]
            if left_beats == right_beats:
                raise GameKitError(
                    f"matchup {left['id']} vs {right['id']} must declare exactly one winner"
                )
    return {
        **_metadata(merged, players=2),
        "match": normalized_match,
        "choices": normalized_choices,
    }


def _normalize_arcade_manifest(value: dict[str, Any]) -> dict[str, Any]:
    allowed = {
        "schema",
        "preset",
        "name",
        "tagline",
        "description",
        "players",
        "theme",
        "vehicle",
        "arena",
        "balance",
        "pickups",
        "pickup_duration_ticks",
        "victory",
    }
    unknown = sorted(set(value) - allowed)
    if unknown:
        raise GameKitError(f"game manifest has unknown fields: {unknown!r}")
    merged = _merge_manifest(value)
    if merged.get("schema") != GAME_KIT_SCHEMA:
        raise GameKitError(f"game manifest schema must be {GAME_KIT_SCHEMA!r}")
    if merged.get("preset") != "arcade":
        raise GameKitError("arcade normalizer received a different preset")
    if merged.get("players") != 2:
        raise GameKitError("arcade requires exactly two players")
    vehicle = merged.get("vehicle")
    if not isinstance(vehicle, dict):
        raise GameKitError("vehicle must be an object")
    vehicle_unknown = sorted(
        set(vehicle) - {"kind", "label", "movement", "primary", "accent"}
    )
    if vehicle_unknown:
        raise GameKitError(f"vehicle has unknown fields: {vehicle_unknown!r}")
    kind = vehicle.get("kind")
    if not isinstance(kind, str) or not _SLUG_RE.fullmatch(kind):
        raise GameKitError("vehicle.kind must be a lowercase slug")
    movement = vehicle.get("movement")
    if movement not in {"ground", "air"}:
        raise GameKitError("vehicle.movement must be ground or air")
    colors: dict[str, str] = {}
    for key in ("primary", "accent"):
        color = vehicle.get(key)
        if not isinstance(color, str) or not _COLOR_RE.fullmatch(color):
            raise GameKitError(f"vehicle.{key} must be a six-digit hex color")
        colors[key] = color.lower()
    arena = merged.get("arena")
    if not isinstance(arena, dict):
        raise GameKitError("arena must be an object")
    arena_unknown = sorted(set(arena) - {"map", "team_size", "friendly_fire"})
    if arena_unknown:
        raise GameKitError(f"arena has unknown fields: {arena_unknown!r}")
    rows = arena.get("map")
    if not isinstance(rows, list) or not 5 <= len(rows) <= 64:
        raise GameKitError("arena.map must contain between 5 and 64 rows")
    if any(not isinstance(row, str) for row in rows):
        raise GameKitError("arena.map rows must be strings")
    width = len(rows[0]) if rows else 0
    if not 5 <= width <= 64 or any(len(row) != width for row in rows):
        raise GameKitError("arena.map must be rectangular and 5 to 64 columns wide")
    tile_set = {"#", "B", "W", "S", "P", "."}
    for index, row in enumerate(rows):
        invalid = sorted(set(row) - tile_set)
        if invalid:
            raise GameKitError(f"arena.map row {index} has invalid tiles: {invalid!r}")
    if any(tile != "#" for tile in rows[0] + rows[-1]):
        raise GameKitError("arena.map top and bottom borders must use #")
    if any(row[0] != "#" or row[-1] != "#" for row in rows):
        raise GameKitError("arena.map left and right borders must use #")
    team_size = _integer(
        arena.get("team_size"), "arena.team_size", minimum=1, maximum=8
    )
    if sum(row.count(".") + row.count("S") + row.count("P") for row in rows) < team_size * 2:
        raise GameKitError("arena.map does not contain enough spawnable cells")
    friendly_fire = arena.get("friendly_fire")
    if not isinstance(friendly_fire, bool):
        raise GameKitError("arena.friendly_fire must be boolean")
    balance = merged.get("balance")
    if not isinstance(balance, dict):
        raise GameKitError("balance must be an object")
    balance_unknown = sorted(
        set(balance) - {"hp", "speed", "fire_cooldown", "bullet_speed"}
    )
    if balance_unknown:
        raise GameKitError(f"balance has unknown fields: {balance_unknown!r}")
    normalized_balance = {
        "hp": _integer(balance.get("hp"), "balance.hp", minimum=1, maximum=20),
        "speed": _integer(
            balance.get("speed"), "balance.speed", minimum=40, maximum=1000
        ),
        "fire_cooldown": _integer(
            balance.get("fire_cooldown"),
            "balance.fire_cooldown",
            minimum=1,
            maximum=60,
        ),
        "bullet_speed": _integer(
            balance.get("bullet_speed"),
            "balance.bullet_speed",
            minimum=100,
            maximum=3000,
        ),
    }
    pickups = merged.get("pickups")
    pickup_values = {"repair", "speed", "rapid", "shield"}
    if (
        not isinstance(pickups, list)
        or any(item not in pickup_values for item in pickups)
        or len(set(pickups)) != len(pickups)
    ):
        raise GameKitError(
            "pickups must be a unique list containing repair, speed, rapid, or shield"
        )
    duration = _integer(
        merged.get("pickup_duration_ticks"),
        "pickup_duration_ticks",
        minimum=10,
        maximum=10000,
    )
    victory = merged.get("victory")
    if not isinstance(victory, dict):
        raise GameKitError("victory must be an object")
    victory_unknown = sorted(
        set(victory) - {"mode", "target_score", "max_ticks"}
    )
    if victory_unknown:
        raise GameKitError(f"victory has unknown fields: {victory_unknown!r}")
    mode = victory.get("mode")
    if mode not in {"elimination", "first_to_score", "survive_ticks"}:
        raise GameKitError(
            "victory.mode must be elimination, first_to_score, or survive_ticks"
        )
    normalized_victory = {
        "mode": mode,
        "target_score": _integer(
            victory.get("target_score"),
            "victory.target_score",
            minimum=1,
            maximum=64,
        ),
        "max_ticks": _integer(
            victory.get("max_ticks"),
            "victory.max_ticks",
            minimum=10,
            maximum=100000,
        ),
    }
    return {
        **_metadata(merged, players=2),
        "vehicle": {
            "kind": kind,
            "label": _text(
                vehicle.get("label"), "vehicle.label", minimum=1, maximum=48
            ),
            "movement": movement,
            **colors,
        },
        "arena": {
            "map": list(rows),
            "team_size": team_size,
            "friendly_fire": friendly_fire,
        },
        "balance": normalized_balance,
        "pickups": list(pickups),
        "pickup_duration_ticks": duration,
        "victory": normalized_victory,
    }


def normalize_manifest(value: Any) -> dict[str, Any]:
    if not isinstance(value, dict):
        raise GameKitError("game manifest must be a JSON object")
    preset = value.get("preset", "duel")
    if preset == "duel":
        return _normalize_duel_manifest(value)
    if preset == "choice-matrix":
        return _normalize_matrix_manifest(value)
    if preset == "arcade":
        return _normalize_arcade_manifest(value)
    raise GameKitError(f"preset must be one of: {', '.join(SUPPORTED_PRESETS)}")


def _build_duel_spec(manifest: dict[str, Any]) -> dict[str, Any]:
    players = int(manifest["players"])
    action_ids = [item["id"] for item in manifest["actions"]]
    return {
        "name": manifest["name"],
        "spec_version": "1.0",
        "description": manifest["description"],
        "type": "game",
        "family": "game-kit-duel",
        "flow": {
            "mode": "authoritative_group",
            "group": {
                "min_participants": players,
                "max_participants": players,
                "allow_late_join": False,
                "recovery_mode": "exact",
                "start_policy": "fixed_full",
                "checkpoint_every_events": 12,
                "max_action_bytes": 4096,
                "max_events_per_action": 16,
            },
        },
        "messages": [
            {
                "name": "game_kit_action",
                "direction": "guest_to_host",
                "fields": {
                    "action": {
                        "type": "enum",
                        "values": ["game_kit_action"],
                        "required": True,
                    },
                    "client_seq": {"type": "integer", "min": 1, "required": True},
                    "payload": {
                        "type": "json",
                        "container": "object",
                        "max_total_bytes": 4096,
                        "required": True,
                    },
                },
            },
            {
                "name": "game_kit_frame",
                "direction": "host_to_guest",
                "fields": {
                    "action": {
                        "type": "enum",
                        "values": ["game_kit_frame"],
                        "required": True,
                    },
                    "frame": {
                        "type": "json",
                        "container": "object",
                        "max_total_bytes": 1048576,
                        "required": True,
                    },
                },
            },
        ],
        "rules": {
            "game_kit": manifest,
            "action_contract": {
                "kind": ["play", "concede"],
                "moves": action_ids,
                "target": "target_public_key is required for damage when more than one rival is active",
            },
            "authority": (
                "The current Leader validates turn ownership, energy, targets, damage, "
                "shield absorption, elimination, turn limits, and the terminal outcome."
            ),
            "recovery": (
                "The complete public arena state is checkpointed and restored exactly after "
                "a Leader change; leader_epoch remains the fencing token."
            ),
        },
        "decision": {
            "mode": "auto",
            "control": "structured_game_kit_actions",
        },
    }


def _build_matrix_spec(manifest: dict[str, Any]) -> dict[str, Any]:
    choice_ids = [item["id"] for item in manifest["choices"]]
    max_rounds = int(manifest["match"]["max_rounds"])
    rounds_to_win = int(manifest["match"]["rounds_to_win"])
    return {
        "name": manifest["name"],
        "spec_version": "1.0",
        "description": manifest["description"],
        "type": "game",
        "family": "game-kit-choice-matrix",
        "flow": {
            "mode": "simultaneous_round",
            "round": {
                "value_field": "choice",
                "value_type_ref": "reveal.fields.choice",
            },
            "phases": [
                {
                    "phase": "join",
                    "exchange": [
                        {"message": "join", "direction": "guest_to_host"},
                        {"message": "ready", "direction": "host_to_guest"},
                    ],
                },
                {
                    "phase": "round",
                    "repeat": "best_of",
                    "exchange": [
                        {"message": "commit", "direction": "host_to_guest"},
                        {"message": "commit", "direction": "guest_to_host"},
                        {"message": "reveal", "direction": "host_to_guest"},
                        {"message": "reveal", "direction": "guest_to_host"},
                        {"message": "round_result", "direction": "host_to_guest"},
                    ],
                },
            ],
        },
        "messages": [
            {
                "name": "join",
                "direction": "guest_to_host",
                "fields": {
                    "action": {
                        "type": "enum",
                        "values": ["join"],
                        "required": True,
                    },
                    "best_of": {
                        "type": "integer",
                        "min": 1,
                        "max": max_rounds,
                        "required": True,
                    },
                },
            },
            {
                "name": "ready",
                "direction": "host_to_guest",
                "fields": {
                    "action": {
                        "type": "enum",
                        "values": ["ready"],
                        "required": True,
                    },
                    "best_of": {"type": "integer", "required": True},
                    "rounds_to_win": {"type": "integer", "required": True},
                },
            },
            {
                "name": "commit",
                "direction": "both",
                "fields": {
                    "action": {
                        "type": "enum",
                        "values": ["commit"],
                        "required": True,
                    },
                    "round": {"type": "integer", "min": 0, "required": True},
                    "hash": {"type": "hash", "required": True},
                },
            },
            {
                "name": "reveal",
                "direction": "both",
                "fields": {
                    "action": {
                        "type": "enum",
                        "values": ["reveal"],
                        "required": True,
                    },
                    "round": {"type": "integer", "min": 0, "required": True},
                    "choice": {
                        "type": "enum",
                        "values": choice_ids,
                        "required": True,
                    },
                    "nonce": {"type": "nonce", "required": True},
                },
            },
            {
                "name": "round_result",
                "direction": "host_to_guest",
                "fields": {
                    "action": {
                        "type": "enum",
                        "values": ["round_result"],
                        "required": True,
                    },
                    "round": {"type": "integer", "min": 0, "required": True},
                    "host_choice": {
                        "type": "enum",
                        "values": choice_ids,
                        "required": True,
                    },
                    "guest_choice": {
                        "type": "enum",
                        "values": choice_ids,
                        "required": True,
                    },
                    "round_winner": {
                        "type": "enum",
                        "values": ["host", "guest", "draw"],
                        "required": True,
                    },
                    "host_score": {"type": "integer", "min": 0, "required": True},
                    "guest_score": {"type": "integer", "min": 0, "required": True},
                    "game_over": {"type": "boolean", "required": True},
                    "game_winner": {
                        "type": "enum",
                        "values": ["host", "guest", "draw", "none"],
                        "required": True,
                    },
                },
            },
        ],
        "rules": {
            "game_kit": manifest,
            "authority": (
                "The simultaneous-round engine owns commit, reveal, nonce, hash, "
                "and barrier validation. The local Game Kit runtime applies only the "
                "content-addressed choice matrix and terminal score."
            ),
            "matchups": {
                item["id"]: list(item["beats"]) for item in manifest["choices"]
            },
        },
        "decision": {
            "mode": "auto",
            "timeout_seconds": 120,
            "timeout_action": "fallback",
        },
        "timing": {"mode": "simultaneous", "min_think_seconds": 0, "max_think_seconds": 2},
        "parameters": {
            "best_of": {
                "type": "integer",
                "min": max_rounds,
                "max": max_rounds,
                "default": max_rounds,
            },
            "rounds_to_win": {
                "type": "integer",
                "min": rounds_to_win,
                "max": rounds_to_win,
                "default": rounds_to_win,
            },
        },
    }


def _realtime_messages() -> list[dict[str, Any]]:
    return [
        {
            "name": "rt_join",
            "direction": "guest_to_host",
            "fields": {
                "action": {"type": "enum", "values": ["rt_join"], "required": True},
                "wire_version": {"type": "integer", "min": 1, "max": 1, "required": True},
                "ruleset_hash": {"type": "hash", "required": True},
                "match_config_hash": {"type": "hash", "required": True},
            },
        },
        {
            "name": "rt_command",
            "direction": "guest_to_host",
            "fields": {
                "action": {"type": "enum", "values": ["rt_command"], "required": True},
                "seq": {"type": "integer", "min": 1, "required": True},
                "target_tick": {"type": "integer", "min": 1, "required": True},
                "commands": {"type": "json", "container": "array", "max_total_bytes": 131072, "required": True},
                "command_hash": {"type": "hash", "required": True},
            },
        },
        {
            "name": "rt_ready",
            "direction": "host_to_guest",
            "fields": {
                "action": {"type": "enum", "values": ["rt_ready"], "required": True},
                "wire_version": {"type": "integer", "min": 1, "max": 1, "required": True},
                "ruleset_hash": {"type": "hash", "required": True},
                "match_config_hash": {"type": "hash", "required": True},
                "config": {"type": "json", "container": "object", "max_total_bytes": 8192, "required": True},
                "frame": {"type": "json", "container": "object", "max_total_bytes": 1048576, "required": True},
            },
        },
        {
            "name": "rt_reject",
            "direction": "host_to_guest",
            "fields": {
                "action": {"type": "enum", "values": ["rt_reject"], "required": True},
                "reason": {"type": "text", "max_length": 256, "required": True},
            },
        },
        {
            "name": "rt_command_ack",
            "direction": "host_to_guest",
            "fields": {
                "action": {"type": "enum", "values": ["rt_command_ack"], "required": True},
                "seq": {"type": "integer", "min": 1, "required": True},
                "target_tick": {"type": "integer", "min": 1, "required": True},
                "status": {"type": "enum", "values": ["accepted", "rejected"], "required": True},
                "received_at_tick": {"type": "integer", "min": 0, "required": True},
                "command_hash": {"type": "hash", "required": True},
                "reason": {"type": "text", "max_length": 256},
            },
        },
        {
            "name": "rt_frame",
            "direction": "host_to_guest",
            "fields": {
                "action": {"type": "enum", "values": ["rt_frame"], "required": True},
                "frame": {"type": "json", "container": "object", "max_total_bytes": 1048576, "required": True},
            },
        },
    ]


def _build_arcade_spec(manifest: dict[str, Any]) -> dict[str, Any]:
    return {
        "name": manifest["name"],
        "spec_version": "1.0",
        "description": manifest["description"],
        "type": "game",
        "family": "game-kit-arcade",
        "flow": {
            "mode": "authoritative_realtime",
            "realtime": {
                "tick_rate_hz": 10,
                "input_delay_ticks": 3,
                "snapshot_every_ticks": 1,
                "max_command_lead_ticks": 30,
                "max_commands_per_frame": 32,
                "disconnect_policy": "abort",
            },
        },
        "messages": _realtime_messages(),
        "rules": {
            "game_kit": manifest,
            "authority": (
                "Host advances the fixed-rate integer simulation. Guests submit only "
                "bounded future command frames; every complete world frame is hash chained."
            ),
            "movement": (
                "Ground vehicles collide with water, brick, and steel. Air vehicles "
                "cross water and brick while the steel border remains authoritative."
            ),
            "pickups": (
                "The blueprint selects a bounded rotation of repair, speed, rapid-fire, "
                "and shield cores."
            ),
            "victory": manifest["victory"],
        },
        "decision": {"mode": "auto", "control": "macro_orders_to_agent_micro_commands"},
    }


def _build_spec(manifest: dict[str, Any]) -> dict[str, Any]:
    preset = manifest["preset"]
    if preset == "duel":
        return _build_duel_spec(manifest)
    if preset == "choice-matrix":
        return _build_matrix_spec(manifest)
    if preset == "arcade":
        return _build_arcade_spec(manifest)
    raise GameKitError(f"unsupported preset: {preset}")


def _asset_text(relative: str) -> str:
    asset = resources.files("aigenora.gamekit").joinpath("templates", relative)
    return asset.read_text(encoding="utf-8")


def _render_hooks(manifest: dict[str, Any]) -> str:
    preset = manifest["preset"]
    if preset in {"duel", "choice-matrix"}:
        return _asset_text(f"{preset}/hooks.py.txt")
    if preset == "arcade":
        blueprint = pprint.pformat(manifest, sort_dicts=True, width=100)
        return (
            "from __future__ import annotations\n\n"
            "from aigenora.gamekit.runtimes.arcade_v1 import ArcadeRuntimeV1\n"
            "from aigenora.proto.hooks import ProtocolHooks\n\n\n"
            "class Hooks(ArcadeRuntimeV1, ProtocolHooks):\n"
            "    SUPPORTED_CONTROL_MODES = (\"autonomous\", \"hybrid\")\n"
            f"    BLUEPRINT = {blueprint}\n"
        )
    raise GameKitError(f"unsupported preset: {preset}")


def _inspect_generated_hooks(
    manifest: dict[str, Any], hooks_source: bytes
) -> tuple[list[str], list[str]]:
    if manifest["preset"] == "arcade":
        # The Arcade adapter can import the trusted local runtime, but received
        # P2P hooks cannot. Keep those two capability boundaries independent.
        if hooks_source != _render_hooks(manifest).encode("utf-8"):
            raise GameKitError(
                "generated arcade adapter differs from the trusted template"
            )
        from aigenora.gamekit.runtimes.arcade_v1 import ArcadeRuntimeV1

        methods = sorted(
            name
            for name in dir(ArcadeRuntimeV1)
            if name.startswith("proto_")
            and callable(getattr(ArcadeRuntimeV1, name))
        )
        modes = ["autonomous", "hybrid"]
        return methods, modes

    # Standalone templates also satisfy the stricter received-bundle source
    # contract, which catches accidental capability expansion.
    from aigenora.agent.protocol_bundle import inspect_hooks_source

    inspection = inspect_hooks_source(hooks_source)
    return list(inspection.methods), list(inspection.supported_control_modes)


def _render_ui(manifest: dict[str, Any]) -> str:
    return _asset_text(f"{manifest['preset']}/index.html")


def _marker(protocol_id: str, manifest: dict[str, Any]) -> dict[str, Any]:
    return {
        "schema": BUILD_MARKER_SCHEMA,
        "source_kind": "local_blueprint",
        "runtime_version": 1,
        "preset": manifest["preset"],
        "protocol_id": protocol_id,
        "generated_files": ["hooks.py", "spec.json", "ui/index.html"],
    }


def has_game_blueprint(spec: Any) -> bool:
    if not isinstance(spec, dict):
        return False
    rules = spec.get("rules")
    return isinstance(rules, dict) and isinstance(rules.get("game_kit"), dict)


def inspect_game_spec(spec_or_path: dict[str, Any] | str | Path) -> dict[str, Any]:
    if isinstance(spec_or_path, dict):
        spec = copy.deepcopy(spec_or_path)
    else:
        source = Path(spec_or_path)
        if source.is_dir():
            source = source / "spec.json"
        spec = load_spec(source)
    protocol_id = protocol_hash_from_obj(spec)
    if not has_game_blueprint(spec):
        return {
            "schema": BUILD_MARKER_SCHEMA,
            "status": "not_game_kit",
            "recognized": False,
            "protocol_id": protocol_id,
            "supported_presets": list(SUPPORTED_PRESETS),
        }
    try:
        game = _game_config_from_spec(spec)
    except GameKitError as exc:
        return {
            "schema": BUILD_MARKER_SCHEMA,
            "status": "unsupported",
            "recognized": True,
            "protocol_id": protocol_id,
            "reason": str(exc),
            "supported_presets": list(SUPPORTED_PRESETS),
        }
    return {
        "schema": BUILD_MARKER_SCHEMA,
        "status": "ready",
        "recognized": True,
        "protocol_id": protocol_id,
        "preset": game["preset"],
        "name": game["name"],
        "players": game["players"],
        "theme": game["theme"],
        "materialization": "deterministic_local_runtime_v1",
        "requires_remote_code": False,
    }


def _sha256_text(value: str) -> str:
    return hashlib.sha256(value.encode("utf-8")).hexdigest()


def _write_text_atomic(path: Path, value: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    handle, temporary_value = tempfile.mkstemp(prefix=f".{path.name}.", dir=path.parent)
    temporary = Path(temporary_value)
    try:
        with os.fdopen(handle, "w", encoding="utf-8", newline="\n") as stream:
            stream.write(value)
        os.replace(temporary, path)
    finally:
        if temporary.exists():
            temporary.unlink()


def _read_marker(protocol_dir: Path) -> dict[str, Any] | None:
    try:
        value = json.loads((protocol_dir / BUILD_MARKER).read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return None
    return value if isinstance(value, dict) else None


def materialize_protocol(
    protocol_dir: str | Path,
    *,
    protocol_id: str | None = None,
    include_ui: bool = True,
    force: bool = False,
    run_smoke: bool = False,
) -> dict[str, Any]:
    """Materialize trusted local hooks/UI from a content-addressed Game Kit spec.

    No executable bytes are accepted from the protocol author. Existing custom hooks
    are preserved; only a pristine generated skeleton or a prior matching Game Kit
    build can be replaced.
    """

    started = time.perf_counter()
    root = Path(protocol_dir).resolve()
    spec_path = root / "spec.json"
    if not spec_path.is_file():
        raise GameKitError(f"spec.json not found: {spec_path}")
    spec = load_spec(spec_path)
    actual_protocol_id = protocol_hash_from_obj(spec)
    if protocol_id is not None and protocol_id != actual_protocol_id:
        raise GameKitError(
            f"protocol hash mismatch: expected {protocol_id}, got {actual_protocol_id}"
        )
    game = _game_config_from_spec(spec)
    hooks_text = _render_hooks(game)
    ui_text = _render_ui(game)
    compile(hooks_text, str(root / "hooks.py"), "exec")
    hooks_methods, supported_control_modes = _inspect_generated_hooks(
        game, hooks_text.encode("utf-8")
    )
    existing_marker = _read_marker(root)
    matching_build = bool(
        existing_marker
        and existing_marker.get("schema") == BUILD_MARKER_SCHEMA
        and existing_marker.get("protocol_id") == actual_protocol_id
    )
    hooks_path = root / "hooks.py"
    hooks_status = "unchanged"
    if hooks_path.exists():
        existing_hooks = hooks_path.read_text(encoding="utf-8")
        if existing_hooks != hooks_text:
            from aigenora.agent.skeleton import detect_pristine

            pristine = bool(detect_pristine(root).get("pristine"))
            generated_hashes = (
                existing_marker.get("generated_hashes")
                if isinstance(existing_marker, dict)
                else None
            )
            unmodified_build = bool(
                matching_build
                and isinstance(generated_hashes, dict)
                and generated_hashes.get("hooks.py") == _sha256_text(existing_hooks)
            )
            if not (pristine or unmodified_build or force):
                raise GameKitError(
                    f"refusing to overwrite custom hooks.py in {root}"
                )
            _write_text_atomic(hooks_path, hooks_text)
            hooks_status = "replaced_pristine" if pristine else "updated"
    else:
        _write_text_atomic(hooks_path, hooks_text)
        hooks_status = "created"

    ui_status = "skipped"
    ui_path = root / "ui" / "index.html"
    if include_ui:
        if not ui_path.exists():
            _write_text_atomic(ui_path, ui_text)
            ui_status = "created"
        elif ui_path.read_text(encoding="utf-8") == ui_text:
            ui_status = "unchanged"
        elif (
            matching_build
            and isinstance(existing_marker.get("generated_hashes"), dict)
            and existing_marker["generated_hashes"].get("ui/index.html")
            == _sha256_text(ui_path.read_text(encoding="utf-8"))
        ) or force:
            _write_text_atomic(ui_path, ui_text)
            ui_status = "updated"
        else:
            ui_status = "preserved_existing"

    marker = _marker(actual_protocol_id, game)
    marker["generated_hashes"] = {
        "hooks.py": _sha256_text(hooks_text),
        "ui/index.html": _sha256_text(ui_text),
    }
    _write_text_atomic(
        root / BUILD_MARKER,
        json.dumps(marker, ensure_ascii=False, indent=2, sort_keys=True) + "\n",
    )
    smoke = _smoke_game_bundle(root) if run_smoke else {"status": "skipped"}
    return {
        "schema": BUILD_MARKER_SCHEMA,
        "status": "materialized",
        "source_kind": "local_blueprint",
        "protocol_id": actual_protocol_id,
        "preset": game["preset"],
        "name": game["name"],
        "hooks": hooks_status,
        "ui": ui_status,
        "hooks_methods": hooks_methods,
        "supported_control_modes": supported_control_modes,
        "smoke": smoke,
        "elapsed_ms": round((time.perf_counter() - started) * 1000, 3),
    }


def _assert_replaceable(output: Path) -> None:
    if output.is_symlink():
        raise GameKitError("refusing to replace a symlinked output directory")
    marker_path = output / BUILD_MARKER
    try:
        marker = json.loads(marker_path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as exc:
        raise GameKitError(
            f"refusing to replace an unmarked directory: {output}"
        ) from exc
    if marker.get("schema") != BUILD_MARKER_SCHEMA:
        raise GameKitError(f"refusing to replace an unknown build directory: {output}")


def _install_stage(stage: Path, output: Path, *, force: bool) -> None:
    if not output.exists():
        os.replace(stage, output)
        return
    if not force:
        raise GameKitError(f"output already exists; pass --force to replace it: {output}")
    _assert_replaceable(output)
    backup = output.with_name(f".{output.name}.game-kit-backup-{uuid.uuid4().hex}")
    os.replace(output, backup)
    try:
        os.replace(stage, output)
    except Exception:
        os.replace(backup, output)
        raise
    shutil.rmtree(backup)


def _game_config_from_spec(spec: dict[str, Any]) -> dict[str, Any]:
    rules = spec.get("rules")
    config = rules.get("game_kit") if isinstance(rules, dict) else None
    normalized = normalize_manifest(config)
    if normalized != config:
        raise GameKitError("rules.game_kit must be a fully normalized manifest")
    return normalized


def _next_target(state: dict[str, Any], actor: str) -> str | None:
    order = list(state.get("turn_order") or [])
    if actor not in order:
        return None
    start = order.index(actor)
    players = state.get("players") or {}
    for offset in range(1, len(order) + 1):
        candidate = order[(start + offset) % len(order)]
        if candidate != actor and (players.get(candidate) or {}).get("alive") is True:
            return candidate
    return None


def choose_preview_action(state: dict[str, Any]) -> dict[str, Any]:
    actor = str(state.get("current_player") or "")
    player = (state.get("players") or {}).get(actor) or {}
    game = state.get("game") or {}
    energy = int(player.get("energy", 0))
    actions = list(game.get("actions") or [])
    affordable = [item for item in actions if int(item.get("cost", 0)) <= energy]
    damage = [
        item
        for item in affordable
        if item.get("effect") in {"damage", "damage_all"}
    ]
    selected = (damage or affordable)[0]
    action: dict[str, Any] = {"kind": "play", "move": selected["id"]}
    if selected.get("effect") == "damage":
        target = _next_target(state, actor)
        if target:
            action["target_public_key"] = target
    return action


def _smoke_duel_bundle(protocol_dir: Path) -> dict[str, Any]:
    started = time.perf_counter()
    spec = load_spec(protocol_dir / "spec.json")
    config = _game_config_from_spec(spec)
    with tempfile.TemporaryDirectory(prefix="aigenora-game-kit-smoke-") as root_value:
        root = Path(root_value)
        keys = [
            keygen(str(root / f"member-{index}"), force=True)
            for index in range(int(config["players"]))
        ]
        members = [
            {
                "member_id": f"member-{index}",
                "public_key": key.public_key,
                "seat": index,
                "status": "active",
            }
            for index, key in enumerate(keys)
        ]
        authority = GroupAuthority(
            spec=spec,
            hooks=load_hooks(protocol_dir),
            options={},
            state_dir=root / "leader-0",
            group_id="game-kit-smoke",
            leader_public_key=keys[0].public_key,
            leader_epoch=0,
            membership_version=len(members),
            members=members,
            keypair=keys[0],
        )
        migrations = 0
        turns = 0
        maximum = int(config["combat"]["max_turns"]) + len(members) * 2
        while not authority.completed and turns < maximum:
            actor = str(authority.state["current_player"])
            action = choose_preview_action(authority.state)
            _envelopes, receipt = authority.apply_input(
                actor_public_key=actor,
                client_seq=authority.last_client_seq.get(actor, 0) + 1,
                action=action,
            )
            if receipt.get("status") != "accepted":
                raise GameKitError("generated game smoke action was not accepted")
            turns += 1
            if turns == 2 and not authority.completed:
                checkpoint = authority.checkpoint()
                authority = GroupAuthority(
                    spec=spec,
                    hooks=load_hooks(protocol_dir),
                    options={},
                    state_dir=root / "leader-1",
                    group_id="game-kit-smoke",
                    leader_public_key=keys[1].public_key,
                    leader_epoch=1,
                    membership_version=len(members),
                    members=members,
                    keypair=keys[1],
                    checkpoint=checkpoint,
                )
                migrations += 1
        if not authority.completed or not authority.outcome:
            raise GameKitError("generated game smoke did not reach a terminal outcome")
        return {
            "status": "passed",
            "turns": turns,
            "outcome": authority.outcome,
            "leader_migrations": migrations,
            "final_seq": authority.seq,
            "elapsed_ms": round((time.perf_counter() - started) * 1000, 3),
        }


def _smoke_matrix_bundle(protocol_dir: Path) -> dict[str, Any]:
    started = time.perf_counter()
    spec = load_spec(protocol_dir / "spec.json")
    game = _game_config_from_spec(spec)
    with tempfile.TemporaryDirectory(prefix="aigenora-game-kit-matrix-") as root_value:
        root = Path(root_value)
        host = load_hooks(protocol_dir)
        guest = load_hooks(protocol_dir)
        host.proto_init({}, "host", [], root / "host", {"mode": "auto"})
        guest.proto_init({}, "guest", [], root / "guest", {"mode": "auto"})
        choices = [item["id"] for item in game["choices"]]
        rounds = 0
        completed = False
        outcome = "none"
        while rounds < int(game["match"]["max_rounds"]):
            host_value = choices[rounds % len(choices)]
            guest_value = choices[(rounds + 1) % len(choices)]
            result = host.proto_round_judge(rounds, host_value, guest_value, {})
            if not isinstance(result.response, dict):
                raise GameKitError("generated choice matrix judge returned no response")
            guest.proto_guest_handle(result.response)
            rounds += 1
            if result.completed:
                completed = True
                outcome = str(result.response.get("game_winner") or "none")
                break
        if not completed or outcome == "none":
            raise GameKitError("generated choice matrix smoke did not complete")
        return {
            "status": "passed",
            "rounds": rounds,
            "outcome": outcome,
            "commit_reveal_contract": True,
            "elapsed_ms": round((time.perf_counter() - started) * 1000, 3),
        }


def _smoke_arcade_bundle(protocol_dir: Path) -> dict[str, Any]:
    started = time.perf_counter()
    spec = load_spec(protocol_dir / "spec.json")
    game = _game_config_from_spec(spec)
    with tempfile.TemporaryDirectory(prefix="aigenora-game-kit-arcade-") as root_value:
        root = Path(root_value)
        host = load_hooks(protocol_dir)
        guest = load_hooks(protocol_dir)
        host.proto_init({}, "host", [], root / "host", {"mode": "auto"})
        guest.proto_init({}, "guest", [], root / "guest", {"mode": "auto"})
        state = host.proto_realtime_initial_state()
        outcome = "none"
        ticks = 0
        for tick in range(1, int(game["victory"]["max_ticks"]) + 1):
            host_commands = host.proto_realtime_validate_commands(
                "host", host.proto_realtime_commands(state, tick), state, tick
            )
            guest_commands = guest.proto_realtime_validate_commands(
                "guest", guest.proto_realtime_commands(state, tick), state, tick
            )
            step = host.proto_realtime_step(
                state,
                tick,
                {"host": host_commands, "guest": guest_commands},
            )
            state = step["state"]
            outcome = str(step.get("outcome") or "none")
            ticks = tick
            if outcome != "none":
                break
        if outcome == "none" or not state.get("game_over"):
            raise GameKitError("generated arcade smoke did not complete")
        audit = host.proto_realtime_audit_outcome(
            {"state": state, "outcome": outcome, "events": state.get("events") or []}
        )
        if audit.get("status") != "passed":
            raise GameKitError("generated arcade terminal audit failed")
        return {
            "status": "passed",
            "ticks": ticks,
            "outcome": outcome,
            "vehicle": game["vehicle"]["kind"],
            "movement": game["vehicle"]["movement"],
            "pickups": list(game["pickups"]),
            "elapsed_ms": round((time.perf_counter() - started) * 1000, 3),
        }


def _smoke_game_bundle(protocol_dir: Path) -> dict[str, Any]:
    spec = load_spec(protocol_dir / "spec.json")
    preset = _game_config_from_spec(spec)["preset"]
    if preset == "duel":
        return _smoke_duel_bundle(protocol_dir)
    if preset == "choice-matrix":
        return _smoke_matrix_bundle(protocol_dir)
    if preset == "arcade":
        return _smoke_arcade_bundle(protocol_dir)
    raise GameKitError(f"unsupported preset: {preset}")


def validate_game_bundle(
    protocol_dir: str | Path,
    *,
    run_smoke: bool = True,
) -> dict[str, Any]:
    started = time.perf_counter()
    root = Path(protocol_dir).resolve()
    spec_path = root / "spec.json"
    hooks_path = root / "hooks.py"
    ui_path = root / "ui" / "index.html"
    for required in (spec_path, hooks_path, ui_path):
        if not required.is_file():
            raise GameKitError(f"generated game is missing {required.relative_to(root)}")
    spec = load_spec(spec_path)
    config = _game_config_from_spec(spec)
    hooks_source = hooks_path.read_bytes()
    compile(hooks_source.decode("utf-8"), str(hooks_path), "exec")
    hooks_methods, supported_control_modes = _inspect_generated_hooks(
        config, hooks_source
    )
    ui = ui_path.read_text(encoding="utf-8")
    for marker in (
        "parent.postMessage",
        'type:"hello"',
        "@media",
        "data-theme",
    ):
        if marker not in ui:
            raise GameKitError(f"generated UI is missing bridge marker: {marker}")
    bridge_marker = {
        "duel": 'request("action"',
        "choice-matrix": 'request("decide"',
        "arcade": 'request("orders"',
    }[config["preset"]]
    if bridge_marker not in ui:
        raise GameKitError(f"generated UI is missing bridge marker: {bridge_marker}")
    if "http://" in ui or "https://" in ui:
        raise GameKitError("generated UI must not load external resources")
    protocol_id = protocol_hash_from_obj(spec)
    smoke = _smoke_game_bundle(root) if run_smoke else {"status": "skipped"}
    return {
        "schema": BUILD_MARKER_SCHEMA,
        "status": "passed",
        "preset": config["preset"],
        "protocol_id": protocol_id,
        "players": config["players"],
        "theme": config["theme"],
        "files": ["hooks.py", "spec.json", "ui/index.html"],
        "hooks_methods": hooks_methods,
        "supported_control_modes": supported_control_modes,
        "smoke": smoke,
        "elapsed_ms": round((time.perf_counter() - started) * 1000, 3),
    }


def compile_game(
    output: str | Path,
    manifest: dict[str, Any] | None = None,
    *,
    force: bool = False,
) -> dict[str, Any]:
    started = time.perf_counter()
    normalized = normalize_manifest(manifest or {})
    spec = _build_spec(normalized)
    protocol_id = protocol_hash_from_obj(spec)
    destination = Path(output).resolve()
    destination.parent.mkdir(parents=True, exist_ok=True)
    stage = Path(
        tempfile.mkdtemp(prefix=".aigenora-game-kit-", dir=destination.parent)
    )
    installed = False
    try:
        (stage / "ui").mkdir()
        hooks_text = _render_hooks(normalized)
        ui_text = _render_ui(normalized)
        (stage / "spec.json").write_text(
            json.dumps(spec, ensure_ascii=False, indent=2, sort_keys=True) + "\n",
            encoding="utf-8",
        )
        (stage / "hooks.py").write_text(
            hooks_text, encoding="utf-8", newline="\n"
        )
        (stage / "ui" / "index.html").write_text(
            ui_text, encoding="utf-8", newline="\n"
        )
        validation = validate_game_bundle(stage, run_smoke=True)
        marker = _marker(protocol_id, normalized)
        marker["generated_hashes"] = {
            "hooks.py": _sha256_text(hooks_text),
            "ui/index.html": _sha256_text(ui_text),
        }
        (stage / BUILD_MARKER).write_text(
            json.dumps(
                marker,
                ensure_ascii=False,
                indent=2,
                sort_keys=True,
            )
            + "\n",
            encoding="utf-8",
        )
        _install_stage(stage, destination, force=force)
        installed = True
    finally:
        if not installed and stage.exists():
            shutil.rmtree(stage, ignore_errors=True)
    elapsed_ms = round((time.perf_counter() - started) * 1000, 3)
    host_control_mode = "hybrid" if normalized["preset"] == "arcade" else "human"
    return {
        **validation,
        "output": str(destination),
        "elapsed_ms": elapsed_ms,
        "next": {
            "test": f'python -m aigenora protocol test "{destination}"',
            "host": (
                f'python -m aigenora host --protocol-dir "{destination}" '
                f"--control-mode {host_control_mode} --web auto"
            ),
            "friend_join": (
                "Publish a normal invitation without --share-bundle; "
                "the Guest materializes Game Kit locally from spec.json."
            ),
        },
    }
